esphome:
  name: idoo-12pod

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Floo Network"
  password: "thisisthekey!"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Idoo-12Pod Fallback Hotspot"
    password: "S6TbBHzTgi8Q"

captive_portal:
    
switch:
  - platform: gpio
    pin: D5
    name: "Fan"
    icon: "mdi:fan"
  - platform: gpio
    pin: D6
    name: "Water pump"
    icon: "mdi:pump"
  - platform: gpio
    pin:
      number: D8
    name: "White/Red light"
    id: white_red_light
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: D7
    name: "Blue light"
    id: blue_light
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Light - vegetables (W/R/B)"
    icon: "mdi:led-strip"
    lambda: |-
      if (id(white_red_light).state && id(blue_light).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: white_red_light
      - switch.turn_on: blue_light
    turn_off_action:
      - switch.turn_off: white_red_light
      - switch.turn_off: blue_light
    id: light_vegetables
  - platform: template
    name: "Light - flowers & fruits (W/R)"
    icon: "mdi:led-strip"
    lambda: |-
      if (id(white_red_light).state && !id(blue_light).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: white_red_light
      - switch.turn_off: blue_light
    turn_off_action:
      - switch.turn_off: white_red_light
      - switch.turn_off: blue_light
    id: light_flowers_fruits