esphome:
  name: solismanager

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0
  level: NONE

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Floo Network"
  password: "thisisthekey!"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solismanager Fallback Hotspot"
    password: "thisisthekey!"

captive_portal:

mqtt:
  broker: 192.168.0.200
  username: solis_esphome
  password: solis_esphome
  topic_prefix: esphome_solis
    
uart:
  id: mod_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: GPIO5
  uart_id: mod_bus
  id: mod_bus_solis

modbus_controller:
  - id: solis
    ## the Modbus device addr
    address: 0x1
    modbus_id: mod_bus_solis
    setup_priority: -10
    update_interval: 10s
    command_throttle: 300ms

sensor:
  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_active_power
    name: "Active power"
    address: 3004
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 0
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_internal_temperature
    name: "Internal temperature"
    address: 3041
    unit_of_measurement: "C"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: "mdi:thermometer"

  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_energy_today
    name: "Energy today"
    address: 3014
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: "mdi:lightning-bolt"
  
  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_energy_this_month
    name: "Energy this month"
    address: 3010
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 0
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_dc_voltage_1
    name: "DC voltage 1"
    address: 3021
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: "mdi:flash-triangle-outline"

  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_dc_current_1
    name: "DC current 1"
    address: 3022
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_dc_voltage_2
    name: "DC voltage 2"
    address: 3023
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: "mdi:flash-triangle-outline"

  - platform: modbus_controller
    modbus_controller_id: solis
    id: solis_dc_current_2
    name: "DC current 2"
    address: 3024
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: "mdi:sine-wave"