esphome:
  name: "watermeter"
  comment: "Water meter"

esp8266:
  board: d1_mini

# Enable warning logging
logger:
  level: WARN

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watermeter Fallback Hotspot"
    password: !secret fallback_ap_password

mqtt:
  broker: 192.168.0.201
  username: esphome_watermeter
  password: esphome_watermeter
  topic_prefix: esphome_watermeter

captive_portal:

sensor:
  - platform: pulse_counter
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: "Water flow"
    unit_of_measurement: "L"
    device_class: "water"
    state_class: ""
    icon: "mdi:water"
    update_interval: 60s
    use_pcnt: false
    internal_filter: 200ms
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    filters:
      - multiply: 6
    total:
      name: "Water usage total"
      unit_of_measurement: "m³"
      device_class: "water"
      icon: "mdi:water-pump"
      accuracy_decimals: 3
      filters:
        - multiply: 0.01
